### ISSUE TITLE
Receiving a "The file doesn't seem to be an image." Error

### ISSUE THREAD

**Issue by realsnleo** [mosbth/cimage#100]
First off, great plugin. I am getting an issue when applying Filters, especially the ones with commas in them. Re-sizing, gray-scaling and so on work great. But every request with the following URL ends up in an error.

https://localhost/tweet/location-to-img-php/img.php?src=image.jpg&width=430&height=300&crop-to-fit&f=colorize,100,60,0,0

The error is receive is:

Warning: imagejpeg(E:\tweet\vendor\mos\cimage\webroot/../../../../assets/images/cache//_._ct_430_300_cf_q60_f1_f2:-10_f3:-20_f4:120:60:0:0s.jpg): failed to open stream: Invalid argument in E:\tweet\vendor\mos\cimage\CImage.php on line 2128

Warning: filemtime(): stat failed for E:\tweet\vendor\mos\cimage\webroot/../../../../assets/images/cache//_._ct_430_300_cf_q60_f1_f2:-10_f3:-20_f4:120:60:0:0s.jpg in E:\tweet\vendor\mos\cimage\CImage.php on line 2270

Warning: getimagesize(E:\tweet\vendor\mos\cimage\webroot/../../../../assets/images/cache//_._ct_430_300_cf_q60_f1_f2:-10_f3:-20_f4:120:60:0:0s.jpg): failed to open stream: Invalid argument in E:\tweet\vendor\mos\cimage\CImage.php on line 2299
[img.php]
img.php: Uncaught exception:

The file doesn't seem to be an image.

#0 E:\tweet\vendor\mos\cimage\CImage.php(2300): CImage->raiseError('The file doesn'...')
#1 E:\tweet\vendor\mos\cimage\webroot\img.php(994): CImage->output()
#2 {main}

I appreciate any help on this. Thank you.

**Comment by realsnleo** [comment]
Hi,
I figured out the proble. Windows does not like putting colons in filenames. CImage applys the colons while generating the filename. I edited this line in CImage.php

#1224    $filters .= ":".$filter["arg{$i}"];

To:

#1224    $filters .= "-".$filter["arg{$i}"];

Everything is working as intended now. Thanks!!

**Comment by mosbth** [comment]
I'll check it out. Sounds like a good solution.
