### ISSUE TITLE
Running cimage on nginx?

### ISSUE THREAD

**Issue by flobox** [mosbth/cimage#105]
Is anybody runnig cimage in a nginx webserver? 
My questions refers especially on the "Friendly urls" .htaccess - since nginx is not "supporting" .htaccess

**Comment by pshon** [comment]
Hi.
I runing cimage on nginx, but I wrote a wrapper for their tasks.
This is my Nginx config:
 
location /images/ {
   try_files $uri $uri/ @imageresize;
}

location @imageresize {
   include fastcgi_params;
   fastcgi_pass   phpfpm;
   fastcgi_param script_name cimage.php;
   fastcgi_param SCRIPT_FILENAME $document_root/cimage.php;
   fastcgi_param QUERY_STRING file=$uri;
}

**Comment by flobox** [comment]
Ahhh...interesting...I will try this config.

Everything else runs smoothly on nginx for you?

**Comment by pshon** [comment]
very well)

**Comment by mosbth** [comment]
For the .htaccess you could try a online converter for a startpoint.

Original apache `.htaccess`:
```
RewriteRule ^image/(.*)$        img/img.php?src=$1 [QSA,NC,L]
```

I tried two online converters which game me the following suggestions:
```
# nginx configuration
location /image {
rewrite ^/image/(.*)$ /img/img.php?src=$1 break;
}
```
and
```
rewrite ^/image/(.*)$ /img/img.php?src=$1 last;
```

Seems like [Nginx has some rewrite directive](http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#rewrite).

**Comment by flobox** [comment]
Thanks Mikael! I did see the online converter. I will try both solutions!

**Comment by mosbth** [comment]
@flobox feel free to let us now how you solved it.

**Comment by flobox** [comment]
@mosbth Honestly I solved it with your solution. So far everything is working like a charm.
