### ISSUE TITLE
Running cimage with the following .htaccess - security issues?

### ISSUE THREAD

**Issue by flobox** [mosbth/cimage#106]
I have set up cimage on its own subdomain. For example: http://somename.somedomain.com/ points to /cimage/webroot !
Now I would like to run cimage with the following .htaccess:

RewriteEngine on
RewriteRule ^(.*)$        img.php?src=$1 [QSA,NC,L]

Producing the following example URLs:
http://somename.somedomain.com/apple.jpg&w=200 for example.

This will mean that every possible request on the http://somename.somedomain.com/ will always go to the "img.php" - any security problems or potential issues with this? Would you guys recommend doing this?

Thanks for your input again!

**Comment by mosbth** [comment]
You are not doing anything special that requires additional security concerns. You are just using another domain and a minor change in the rewrite rule so its more or less like the standard usage.

There is always concerns. What about /robots.txt /sitemap.xml, potential /favicon.ico? But these are not related to CImage. So, try it out.

**Comment by flobox** [comment]
I am trying :)

Yes you are right - you just pointed it out, that now every potential request on the subdomain (bots, crawlers, etc.) will access / put requests on the img.php (like robots.txt, sitemap.xml, ...). Normally this shouldn't be a problem. We are testing it in the next weeks on our production system - serving a lot of requests by cimage! ;)

By the way: thank you a lot @mosbth for offering cimage to us! Great and very simple image resizer!
