### ISSUE TITLE
HTTP Header: Cache Control?

### ISSUE THREAD

**Issue by flobox** [mosbth/cimage#109]
I did see some code for setting a correct http header - for cache control for example - by cimage.

Unfortunately either on my Apache or nginx testing machine I do not get the http header correct.
Is this working out of the box?

![view http request and response header 2015-10-15 14-58-41](https://cloud.githubusercontent.com/assets/3763232/10514297/41bb04d4-734d-11e5-8cb4-e344c983a7d2.png)

**Comment by mosbth** [comment]
Its the method `CImage::output()` that decides how the header looks like.
https://github.com/mosbth/cimage/blob/v0.7.4/CImage.php#L2236-L2308

It always writes out this part.

```
    header('Last-Modified: ' . $gmdate . " GMT");
```

If the image is not modified, it will answer with 304.

```
if (isset($_SERVER['HTTP_IF_MODIFIED_SINCE']) && strtotime($_SERVER['HTTP_IF_MODIFIED_SINCE']) == $lastModified) {
    header("HTTP/1.0 304 Not Modified");
```

That should be fine for the browser to work with caching the images.

Load the image in the browser for the first time. 200. Reload the page, 304. Force reload the browser with shift-ctrl-r and you get a 200.

**Comment by mosbth** [comment]
There might be an idea to add a optional header entry of "Cache Control". It could be off per default, or saying `Cache-Control: no-cache`. It could then be changed in the config-file, for example to `Cache-Control: max-age=86400`. 

I've previously looked at the ETag but I found no additional improvements over the existing `Last-Modified`.

**Comment by flobox** [comment]
Hi Mikael!

Thank for answering!
Yes the "Last Modified" is there.
Because of this you dont NEED to have Etag - you can - but "Last Modified" should be enough...

It is the same with "Expires" and "Cache-Control: max-age:XYZ" - you could add both, but probably Cache-Control is the better setted solution for the future.

Here is what Googe suggests and what I think would be useful: https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching?hl=en

- Cache-Control:
      - max-age=XYZ
      - public

I think it would be awesome to have the possibility to set Cache-Control within the config file! Really looking forward to this feature!

**Comment by mosbth** [comment]
One can now add a HTTP header for Cache-Control in the config file.

```
       /**
        * Add header for cache control when outputting images.
        *
        * Default value:
        *  cache_control: null, string
        */
        //'cache_control' => "max-age=86400",
```

**Comment by flobox** [comment]
Highly appreciated!! Thank you!

**Comment by katipierson** [comment]
Super! It works!

**Comment by HRarsha** [comment]
I am still seeing empty cache control on output headers, this is set inside img_config 

'cache_control' => "max-age=86400"

below is PSI report

![image](https://github.com/user-attachments/assets/0b0a89f5-3a9d-43a5-a8bf-087f9e844c8c)
