### ISSUE TITLE
Migration from an older script

### ISSUE THREAD

**Issue by manpreet-tolexo** [mosbth/cimage#110]
I am trying to migrate from timthumb.php to cimage.php, but I have filenames with ? and $ in their names, timthumb.php works but cimage gives 500 internal server error

**Comment by mosbth** [comment]
You can always change to development mode to get a better error description, perhaps together with the verbose mode `&verbose`.

In `img_config.php`.
```
    'mode' => 'development',
```

or use `imgd.php` for testing.

In the config-file there is a regexp for whats considered to be a valid filename.

```
    /**
     * A regexp for validating characters in the image or alias filename.
     *
     * Default value:
     *  valid_filename:  '#^[a-z0-9A-Z-/_ \.:]+$#'
     *  valid_aliasname: '#^[a-z0-9A-Z-_]+$#'
     */
     //'valid_filename'  => '#^[a-z0-9A-Z-/_ \.:]+$#',
     //'valid_aliasname' => '#^[a-z0-9A-Z-_]+$#',
```

You could try to uncomment and change the `valid_filename`, like this.

```
     //'valid_filename'  => '#^[a-z0-9A-Z-/_ \.:]+$#',
     'valid_filename'  => '#^[a-z0-9A-Z-/_ \.:\?$]+$#',
```

That should do the trick.

I'm not sure if this should be changed to deafult or not. I'll think about it. Let me know if there are any other issues with merging from thimthumb to cimage.
