### ISSUE TITLE
Support save-as webp

### ISSUE THREAD

**Issue by mosbth** [mosbth/cimage#132]
Requires PHP 5.5.
http://php.net/manual/en/function.imagewebp.php

**Comment by PaulWoitaschek** [comment]
Any news on this? I'd love to see this happen.

**Comment by flobox** [comment]
+1

**Comment by mosbth** [comment]
Nothing done yet. But I'll takea look at it to see what needs to be done.

**Comment by mosbth** [comment]
So, I made a try at it in branch 0715 but failed for some reason. I tried on two different servers with different versions. 

On debian sid with.

```
$ php -version 
PHP 5.6.13-2 (cli)                        
$ php -r 'var_dump(imagecreatefromwebp("webroot/img/lena.webp"));' 
Segmentation fault
```

On debian jessie.

```
$ php -version 
PHP 5.6.20-0+deb8u1 (cli) (built: Apr 27 2016 11:26:05) 
$ php -r 'var_dump(imagecreatefromwebp("webroot/img/lena.webp"));' 
resource(5) of type (gd)
$ php -r 'var_dump(imagecreatefromstring(file_get_contents("webroot/img/lena.webp")));' 
PHP Warning:  imagecreatefromstring(): Data is not in a recognized format in Command line code on line 1 
PHP Stack trace:                                                                                         
PHP   1. {main}() Command line code:0                                                                    
PHP   2. imagecreatefromstring() Command line code:1                                                     
bool(false)                                                                                              
```

Still, the image seems to be displayed okey in a browser supporting it.

[WEBP version of image](https://cimage.se/img/example/lena.webp).

![WEBP version](https://cimage.se/img/example/lena.webp)

JPG version of image.

![JPG version](https://cimage.se/img/example/lena.jpg)

So I got stuck. Lets see if anything pops up.

**Comment by mosbth** [comment]
I made another try and upgraded the PHP version on my debian sid.

```
$ php -version 
PHP 5.6.24-1+b1 (cli)                     
```

It was an improvement and now I have the same error as on my debian jessie.

```
$ php -r 'var_dump(imagecreatefromwebp("webroot/img/lena.webp"));'  
resource(5) of type (gd)                                                                       
```

```
$ php -r 'var_dump(imagecreatefromstring(file_get_contents("webroot/img/lena.webp")));' 
PHP Warning:  imagecreatefromstring(): Data is not in a recognized format in Command line code on line 1           
PHP Stack trace:                                                                                                   
PHP   1. {main}() Command line code:0                                                                              
PHP   2. imagecreatefromstring() Command line code:1                                                               
bool(false)                                                                                                        
```

Seems like `imagecreatefromstring()` does not support WEBP.

So, my guess is that GD partly works with WEBP, but CImage, which uses a bunch of GD techniques, will be a bit harder to make work, for now. My hope is that PHP 5.6.25 will have improved support for WEBP.

I'll do some more tests.

**Comment by mosbth** [comment]
So, for now, having PHP 5.6.24, it seems to work like this.

| What | Status |
|--------|----------|
| `img.php?src=lena.webp` | Ok |
| `img.php?src=lena.webp&so` | Partly ok. Makes a yellow version of the image |
| `img.php?src=lena.webp&w=400` | Partly ok. Makes a yellow version of the image |
| `img.php?src=lena.webp&w=401` | Partly ok. Makes a yellow version of the image |
| `img.php?src=lena.webp&w=402` | Fails, image not displayed |
| `img.php?src=lena.webp&w=403` | Fails, image not displayed |
| `img.php?src=lena.webp&w=404` | Partly ok. Makes a yellow version of the image |
| `img.php?src=lena.webp&q=80` | Fails, image not displayed |
| `img.php?src=lena.webp&q=90` | Partly ok. Makes a yellow version of the image |
| `img.php?src=lena.webp&sa=jpg` | Partly ok. Makes a yellow version of the image |
| `img.php?src=lena.webp&sa=png` | Partly ok. Removes colors from the image |
| `img.php?src=lena.png&sa=webp` | Ok |
| `img.php?src=lena.jpg&sa=webp` | Ok |

Lets say that support for webp images is now partly supported. But one who wants to try it out should have latest possible version of PHP.

If you try it out, let me know. 

I'll close this for now.

**Comment by flobox** [comment]
Just for info!

Using PHP 7.0.x using the above parameters (https://github.com/mosbth/cimage/issues/132#issuecomment-238490115) everything seems to work perfectly with .webp!

**Comment by jzsf** [comment]
I experienced an issue where saving as WEBP sometimes caused the resulting image to be corrupted, i.e., it would display (in Chrome) with the expected dimensions but the image would be completely transparent. To try and reproduce the issue, you can repeatedly save a single image as WEBP but each time with a different width parameter (w=200, w=201, w=202, etc.).

This is an issue with PHP GD's imagewebp(...) function, not cimage. For more info, see: [imagewebp (php) creates corrupted webp files](https://stackoverflow.com/questions/30078090/imagewebp-php-creates-corrupted-webp-files/32221422).

If your system is affected, using the info from the StackOverflow article, you can make a modification of this kind:

Original:
`imagewebp($this->image, $this->cacheFileName, $this->quality);`

Modified:
```
imagewebp($this->image, $this->cacheFileName, $this->quality);
//fix for corrupted WEBPs
if (filesize($this->cacheFileName) % 2 == 1) {
    file_put_contents($this->cacheFileName, "\0", FILE_APPEND);
}
```
Relevant environment details:
Ubuntu 16.04.3
PHP Version 7.0.22-0ubuntu0.16.04.1
GD library Version 2.1.1

**Comment by rosell-dk** [comment]
On this note, I can inform that it seems that old versions of Gd discards the alpha channel when saving webp. More on this here: https://github.com/rosell-dk/webp-convert/issues/238
