### ISSUE TITLE
not working with php 7

### ISSUE THREAD

**Issue by githubmox** [mosbth/cimage#143]
not working with php 7

**Comment by mosbth** [comment]
Ok. Have not yet tested on PHP 7.

What happens? Error output? How to repeat failure?

**Comment by githubmox** [comment]
[img.php]
img.php: Uncaught exception:

Target directory is not writable.

#0 /var/www/html/images/imgd.php(3242): CImage->raiseError('Target director...')
#1 /var/www/html/images/imgd.php(5045): CImage->save()
#2 {main} 

thank you

**Comment by mosbth** [comment]
> http://www.xxxxx.xx/images/imgd.php?src=1.jpg is working

This one does not, per default, create a new cached image in the cache directory.

> http://www.xxxxx.xx/images/imgd.php?src=1.jpg&w=120&h=120 not working

This one creates a cached version of the image in the cache directory.

The error message is saying that the cache directory is not writable. This could be a configuration issue or an issue with PHP 7.

**I will set up a test environment for PHP 7 and try the same thing.**

You can try to do some tests on your own.

You can try to add `&status` to the link to get a verbose output saying if the cache directory is writable or not.

> http://www.xxxxx.xx/images/imgd.php?src=1.jpg&status

You can see what kind of output to expect here: https://cimage.se/doc/check-environment
Here is additional troubleshooting techniques: https://cimage.se/doc/troubleshoot

*Note. The new documentation website for Cimage is work in progress.*

**Comment by githubmox** [comment]
status output:

img.php version = v0.7.9* (2015-12-07)
PHP version = 7.0.6
Running on: Apache/2.4.6 (CentOS) PHP/7.0.6
Allow remote images = 
Cache exists, not writable
Cache remote does not exist
Cache dummy does not exist
Cache srgb does not exist
Alias path writable = 
Extension exif is  loaded.
Extension curl is  loaded.
Extension imagick is NOT loaded.
Extension gd is  loaded.
Array
(
    [GD Version] => bundled (2.1.0 compatible)
    [FreeType Support] => 1
    [FreeType Linkage] => with freetype
    [GIF Read Support] => 1
    [GIF Create Support] => 1
    [JPEG Support] => 1
    [PNG Support] => 1
    [WBMP Support] => 1
    [XPM Support] => 1
    [XBM Support] => 1
    [WebP Support] => 
    [JIS-mapped Japanese Font Support] => 
)

**Comment by githubmox** [comment]
It's working now. thank you

**Comment by mosbth** [comment]
Excellent!
