### ISSUE TITLE
using Cimage to output image on browser

### ISSUE THREAD

**Issue by AngleV** [mosbth/cimage#145]
Hello.
First of all my compliments for your amazing work.

Can you give an example how to use the class without using the imgp.php

e.g

```
$img = new CImage();
** what stuff should i do here **
$img-> output  // output image on browser
```

**Comment by mosbth** [comment]
Have you seen the [last part of img.php](https://github.com/mosbth/cimage/blob/master/webroot/img.php#L1211-L1269)? There is how `img.php` is (finally) using `CImage.php`.

Doing a find on `$img->` in `img.php` will give you 15 more places where `img.php` uses `CImage.php`.

The [docs on the preliminary website](https://cimage.se/doc/cimage-api) might give some more info. That manual page does not seem to be complete though, all 15 places seems not to be there, yet.

I havent myself used the `CImage` class outside of `img.php`, but feel free to give it a try, and let me know how it goes.

**Comment by AngleV** [comment]
ok i thought maybe you allready expose an API to proccess an image using only the class.
Anyway i will test it and let you know 
Thanks
