### ISSUE TITLE
Access Cache Image Directly or Obfuscate Parameter to Prevent Flooding

### ISSUE THREAD

**Issue by marcus-at-localhorst** [mosbth/cimage#159]
Let's say I embed an image like this:
```html
<img src="image.png?width=520&height=580&save-as=gif">
```
and don't want anybody mess around with the parameters, so I am going to rewrite the `src=""` to something like this:

```html
<img src="/cache/images/image.png_520_270_q60_co-1_gif">
```
The issues with this are:
1. exposure of the cache folder (could be rewritten via htaccess)
2. Hen/Egg problem (if cache image doesn't exist, how to reverse engineer the parameters?)

I guess the easiest solution would be to rewrite the params with `base64_encode` and decode them on the img.php side.

Any other idea?

**Comment by mosbth** [comment]
1) Prevent flooding can be done by [write protecting the cache directory](https://cimage.se/doc/implications#readonlycache). This prevents any new cache file from being created. This basically "shuts down" cimage from creating new images, but it  continues to work for all images already generated.

2) Accessing the cache directly could be a feature where one can bypass img.php and use already cached images. A good naming structure of the cache images could ease this usage.

3) Obfuscate (and rewrite) could be a solution and this would most likely also need a good naming structure of the cache file and perhaps some logic to reverse match it to the query string.

4) Another way to work is through the option [`&alias`](https://cimage.se/doc/features-and-options#option-save) where cimage can save a copy of a image in another folder. Perhaps in combination of using [`&password`](https://cimage.se/doc/features-and-options#option-pwd) to prevent other from create images. Here one first creates the resulting image and then uses its alias as the image source.

There are some thoughts on this. More ideas?

**Comment by marcus-at-localhorst** [comment]
When I read about the alias feature I thought of it as the solution. But alias only works with external images only, right?

**Comment by mosbth** [comment]
The option `&alias` works for any image. Its a way to save a copy of the image currently processed.
