### ISSUE TITLE
invalid source filename?

### ISSUE THREAD

**Issue by szunyi** [mosbth/cimage#160]
hi,

if the remote filename contain bracket "(" or ")" then the script said: source filename contains invalid characters

how can i solve this problem?

thanks
bye

**Comment by mosbth** [comment]
You can, through the configfile, edit the regexp that manages what characters are allowed in the filename. 
[See here for the section to edit](https://cimage.se/doc/config-file#security).

Perhaps something like this (uncomment and add `\[` and `\]`).

```php
/**
 * A regexp for validating characters in the image or alias filename.
 *
 * Default value:
 *  valid_filename:  '#^[a-z0-9A-Z-/_ \.:]+$#'
 *  valid_aliasname: '#^[a-z0-9A-Z-_]+$#'
 */
 'valid_filename'  => '#^[a-z0-9A-Z-/_ \.:\[\]]+$#',
 //'valid_aliasname' => '#^[a-z0-9A-Z-_]+$#',
```

**Comment by szunyi** [comment]
thanks
i need this for the round bracket but i modify to this and working: 
#^[a-z0-9A-Z-/_ \.:\(\)]+$#
