### ISSUE TITLE
Focal Point

### ISSUE THREAD

**Issue by katipierson** [mosbth/cimage#161]
Hello,

how did i set the focal point for a picture?
I found only this: ?w=150&crop=200,220,190,300 That means: width, height, start_x and start_y. But i've only a (or many) "new" focal point(s).

Greetings,
Kati

**Comment by mosbth** [comment]
I usually use the [`&area=10,0,0,10`](https://cimage.se/doc/features-and-options#option-crop) to cut away those parts I do not want, that is another rough way of (currently) setting the focal point.

Other ways of setting the focal point is discussed in #59, #79, #94, #96, #124 (features to be implemented).

**Comment by katipierson** [comment]
@mosbth this is a way. But it is an frontend function (twig) for backend things. It is a nice tool and i will have a look at the other threads.

**Comment by mosbth** [comment]
Let me know how you would prefer to do it, from your point of view.
