### ISSUE TITLE
every area zoom in the picture

### ISSUE THREAD

**Issue by katipierson** [mosbth/cimage#162]
I used area=10,0,0,0 for an picture with w=1280 & h=480

The picture was a high size and so i would crop the top to point the face in the center.

It croped from all sides of the picture. Not only from the top. It's the same for area=0,0,10,0 and so on. The picture looks like zoomed in.

If i use a offset for top, i don't want to crop the other sides.

If you use area the negative values or higher positive values you don't get always an image.

High size an 30 works, but with 31 it's doesn't works.

**Comment by mosbth** [comment]
I assume you checked out how it is suppose to work, in the manual section about area:
https://cimage.se/doc/crop-part-of-image#area

If it does not work like intended, could you supply how you are using it?

It should work like this:

Ignore the top 25% of the image.
`?w=150&h=150&crop-to-fit&area=25,0,0,0`
