### ISSUE TITLE
load config file results in error 500

### ISSUE THREAD

**Issue by marcus-at-localhorst** [mosbth/cimage#163]
Hi,
I had some problems using an external config file (imgd_config.php for imgd.php) and I traced it down to this piece of code:

```php
if (is_file($configFile)) {
    $config = require $configFile; // triggers Error 500
   // require $configFile;  // this works
} elseif (!isset($config)) {
    $config = array();
}
```

$config = 1 afterwards - probably as an return that the file was read successfully,

**Comment by mosbth** [comment]
How does your config file looks like?

It should return the config array, like this:

```php
return array(
    'autoloader'   =>  __DIR__ . '/../autoload.php',
    'image_path'        =>  __DIR__ . '/img/',
    'cache_path'        =>  __DIR__ . '/../cache/',
)
```

**Comment by marcus-at-localhorst** [comment]
Thank you, that's it.
I just copied and pasted the array from the main file.
