### ISSUE TITLE
need to update thumb when remote image changed

### ISSUE THREAD

**Issue by activekim** [mosbth/cimage#165]
excuse my english...

without nc option
although remote image changed (with same name) thumbnail not update.

with nc option
always download thumbnail again (last-modified change everytime)

need to check modified time of remote image before using cached thumbnail.

**Comment by mosbth** [comment]
Lets test it.

1. Having car.png.
`img.php?src=car.png`

2. Ensure that the cimage-cached image is up to date (use `nc` / `no-cache`). Just as a starting poing for our test.
`img.php?src=car.png&no-cache`
```
$ ll -r webroot/img/car.png cache/_._car.png_q60_co-1  
-rw-r--r-- 1 mos      mos      245K Oct 23  2015 webroot/img/car.png       
-rw-r--r-- 1 www-data www-data 273K Mar 28 08:44 cache/_._car.png_q60_co-1 
```
The cached version is now newly generated.

3. Change the source image (replace it with another image).
```
$ cp webroot/img/lena.png webroot/img/car.png                         
$ ls -lr webroot/img/{car,car_orig,lena}.png cache/_._car.png_q60_co-1 
-rw-r--r-- 1 mos      mos      464K Mar 28 08:50 webroot/img/car.png                      
-rw-r--r-- 1 www-data www-data 273K Mar 28 08:44 cache/_._car.png_q60_co-1                
```
The source image is updated on the filesystem and is newer than the cimage cached version..

4. Make a request for the image, I'll curl it to avoid browser issues.
```bash
# First check the status of the source and the cache, the source is newest
$ ls -l -r webroot/img/car.png cache/_._car.png_q60_co-1
-rw-r--r-- 1 mos      mos      464K Mar 28 08:56 webroot/img/car.png
-rw-r--r-- 1 www-data www-data 273K Mar 28 08:54 cache/_._car.png_q60_co-1
$ date
Tue Mar 28 09:06:37 CEST 2017

# Make a ordinary request for the image
$ curl --verbose --output car.png "http://localhost/git/cimage/webroot/img.php?src=car.png"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying ::1...
* Connected to localhost (::1) port 80 (#0)
> GET /git/cimage/webroot/img.php?src=car.png HTTP/1.1
> Host: localhost
> User-Agent: curl/7.50.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Tue, 28 Mar 2017 07:06:56 GMT
< Server: Apache/2.4.25 (Debian)
< Last-Modified: Tue, 28 Mar 2017 07:06:56 GMT
< Content-Length: 556219
< Content-Type: image/png
<
{ [16201 bytes data]
100  543k  100  543k    0     0  4066k      0 --:--:-- --:--:-- --:--:-- 4084k
* Connection #0 to host localhost left intact

# The car.png is downloaded and the cimage cache was updated
$ ls -l -r webroot/img/car.png cache/_._car.png_q60_co-1 car.png
-rw-r--r-- 1 mos      mos      464K Mar 28 08:56 webroot/img/car.png
-rw-r--r-- 1 mos      mos      544K Mar 28 09:06 car.png
-rw-r--r-- 1 www-data www-data 544K Mar 28 09:06 cache/_._car.png_q60_co-1

# The file downloaded (car.png) appears to be the same as in the image cache
$ md5sum car.png cache/_._car.png_q60_co-1
3bdddb71126da8d8b6e483d075e68150  car.png
3bdddb71126da8d8b6e483d075e68150  cache/_._car.png_q60_co-1

# Check by looking at the pictures, the look visualy the same
$ firefox car.png cache/_._car.png_q60_co-1 webroot/img/car.png 
```

So, changing the source image will update the cimage cache. Seems to work like expected.

There is no need to use `nc` / `no-cache` option to update the cache.


5. Potential issues

You will most likely get the same result when replacing curl with the web browser AND pressing ctrl-r to doing a reload of the image, or to be really sure doing a shift-ctrl-r to pass the browser cache.

You should also get the same result when "reloading" the page by clicking enter in the browser url-field or when including the image in a html-document. They all should result in a GET of the image.

To avoid issues, and avoid caching issues, use shift-ctrl-r when reloading the image, just to be sure, or test using curl.

Caching issues could be browser caching the image or headers sent by the web server or headers generated from Cimage.

I've seen examples, like this, when one seem to think that cimage does not deliver the latest image, but it seems like it is browser/web server/caching trying to be smart to avoid network traffic, that seems to be the issue.

**Comment by activekim** [comment]
if src is REMOTE file. it skip checking last modified time.
in function download($url) 
if ($this->useCache) it return cached file and skip $this->http->doGet() completely.
have to use nc option to follow doGet() routine and browser download thumb everytime if nc used.

**Comment by mosbth** [comment]
Okey, so we are talking about remote images? That works a bit different.
Tell me how you would like it to work, or expect it to work, and I'll explain how it actually works.

**Comment by activekim** [comment]
whithout nc option
always check modified-time with http head request before checking cache.
or how about make new option like 'ignore remote file time'

**Comment by mosbth** [comment]
For now the file is downloaded once and cached locally.
It saves the header information in the cache, together with the image. 
```
(
    [Date] => Mon, 03 Apr 2017 20:46:17 GMT
    [Max-Age] => 604800
    [Content-Type] => image/jpeg
    [Url] => https://dbwebb.se/image/tema/trad/tree2.jpg
    [Last-Modified] => Mon, 08 Aug 2016 13:02:03 GMT
)
```

It uses Max age to decide when to make a new request for it. Cimage behaves like a browser and listens to the server directive on how long to cache the image.

The option `nc` is like the browsers way to do shift-ctrl-r to reload the page without using cached items.

To get the image, from the remote server, each time its requested, ignoring the server cache directive, seems a bit brutal. 

If your image is updated frequently, try download it with curl/wget and a crontab script instead. That would be a controlled way of downloading it at certain intervals.
