### ISSUE TITLE
Placeholder image on error

### ISSUE THREAD

**Issue by dyanakiev** [mosbth/cimage#172]
Hello,

Is it possible when image is not found, a placeholder with proper size to be shown?
Is this allready a function?

**Comment by mosbth** [comment]
Check out this part of the documentation:
https://cimage.se/doc/select-the-source

And scroll down to "Alternate source as a backup image".

Then click on the link saying how to configure a default backup image by configuration.
https://cimage.se/doc/config-file#src-alt

**Comment by dyanakiev** [comment]
Thanks, this is awesome but i want to set an image that is not within the cache folder how can i do this?

**Comment by mosbth** [comment]
It should work like this.
https://cimage.se/image/not-exists.png (image is missing, error message or 404)
https://cimage.se/image/not-exists.png?src-alt=example/car.png (the alt image is used and displayed)

The alt image is in the image folder here:
https://cimage.se/image/example/car.png (the alt image is in the img directory with all other images)

So the path `example/car.png` should do it in the configuration file.

The alt image "inherits" all other settings, width, height, etc.

**Comment by dyanakiev** [comment]
Thanks this solved the issue :)
