### ISSUE TITLE
Add as composer package

### ISSUE THREAD

**Issue by mosbth** [mosbth/cimage#18]
Add as composer package

**Comment by mfn** [comment]
That would be really great. As it currently stands, integration into other projects isn't very easy and would probably also require change of the layout of files which probably leads to a breaking change. Ideally the class code would also be properly vendor/namespace prefixed.

Would you be interested/willing to do this?

**Comment by mosbth** [comment]
Yep, this is the main task for the next milestone, v0.8. To structure the code/repo for composer, packagist, phpunit, travis, scrutinizer and phpdoc. To make it a bit more "proper".

**Comment by johannesnagl** [comment]
awesome @mosbth! we're really looking forward to this change here at swat.io / walls.io. is there a ETA, or can we help with this issue?

**Comment by mosbth** [comment]
Not really an ETA for this but I can prioritize what to do first with v0.8, or even try to divide v0.8 into two milestones where composer-stuff goes into v0.8 and cimage-nice-to-have-features goes into v0.8.5 or so.

This would mean that a limited v0.8, with focus of moving on to composer, would mean:
- Vendor/namespace/PSR4
- Composer, packagist
- PHP 5.4

There is no harm in also including (and very little effort needed to do so):
- phpdoc
- phpunit (limited to begin with)
- Travis
- Scrutinizer

It sounds like you would like to prioritize these, for ease of integration with other systems and open up for  using Composer as install method. Right?

**Comment by johannesnagl** [comment]
yes, having the option to install cimage with composer would be the number 1 prio.

**Comment by mosbth** [comment]
Added `composer.json` and put it on Packagist at https://packagist.org/packages/mos/cimage.
