### ISSUE TITLE
force regenerate cache image

### ISSUE THREAD

**Issue by yogeshsaroya** [mosbth/cimage#180]
Some time need to rename images. like have a.jpg, b.jpg and when i try to change a.jpg to b.jpg and b.jpg to a.jpg then how to regenerate cache image without changing height/width parameter.

**Comment by mosbth** [comment]
Use the `&nc` or `&no-cache` to ignore the cached image file and generate a new cache file.
https://cimage.se/doc/troubleshoot#no-cache

(and ensure shift-ctrl-r to ignore the browser cache)
