### ISSUE TITLE
Issue when folder or image name have space

### ISSUE THREAD

**Issue by yogeshsaroya** [mosbth/cimage#190]
Hi 
Its not working when folder or image name have space 

like /new folder/abc.png
or 
new-folder/hello world.png

**Comment by mosbth** [comment]
What is the context?

How to repeat?

**Comment by mosbth** [comment]
If I use a default installation of cimage, then I have no issues loading an image `appl e.jpg` with a space in its name.

The following works.
```
img.php?src=appl+e.jpg
```

So does this.
```
img.php?src=appl e.jpg

# Chrome browser rewrites the URL to:
img.php?src=appl%20e.jpg
```

It does not appear to be an issue with cimage.

**Comment by yogeshsaroya** [comment]
I am using only imgd.php file. please advice
