### ISSUE TITLE
External images?

### ISSUE THREAD

**Issue by tommiehansen** [mosbth/cimage#43]
How to use and white list the use of external images? (http://site.com/dir/dir2/image.jpg)

**Comment by mosbth** [comment]
So, I made a shot at it. Here it is, ready for test. Download of remote files are disabled by default and can be enabled in `img_config.php`. See the config-file for details.

Once configured to allow remote download, use it like this:
`http://localhost/mos/git/cimage/webroot/img.php?src=http://dbwebb.se/img/vimmel/jul-dbwebb-2013.jpg&v&w=500`

There are a few things I want to do before announcing this, so the plan is to announce it together with release v0.7. For now its test and evaluation.

Yes, there are a bunch of security concerns when allowing remote download. The major issues should be taken care of already. But there are a few issues that remain within the scope of v0.7.

**Comment by mosbth** [comment]
Consider it as announced.

**Comment by tommiehansen** [comment]
Sorry -- i've just been too busy to try it out unfortunately and haven't had a reason (or time) to deploy another script for images yet. Nice to know that it is implemented though and that will certainly make cImage an easy choice for future projects.
