### ISSUE TITLE
Employ a different file caching strategy regarding file names

### ISSUE THREAD

**Issue by mfn** [mosbth/cimage#86]
The current approach is to literally take the URL, remove some special characters, and write this to disk.

This can easily outrun the maximal allowed file names on todays sytem:
`[26-Feb-2015 07:39:10 UTC] PHP Warning:  file_put_contents(/var/www/tmp/https---someverylongfilename.json): failed to open stream: File name too long in CRemoteImage.php on line 233`

Some directions for best practices:
- use hashing (e.g. sha1, etc.)
- divert files into subdirections

Why I'm mentioned 2): once 1) is solved and you've *many* files, there's usually also a limit on system how many files can be stored in a directory. A common way to solve this, is to take the hash, e.g. `0beec7b5ea3f0fdbc95d0dd47f3c5bc275da8a33` und slice of parts of it for directory names:
- `0beec7b5ea3f0fdbc95d0dd47f3c5bc275da8a33` -> first character `0` -> so create a directory `0` and write file in there

Depending on the "business" there could be multiple levels. Just an idea.

**Comment by mosbth** [comment]
I can change the filenaming for the remote cache. Thats a good idea apparently for the reason you show.

I did not find any support in favor of dividing into subdirectories due to limited number of files allowed in a filesystem. If you have a source, or reference for that, please let me know and I'll check that again.

I will also consider to change the filenaming for the regular cache, but I'll wait with that until a larger revision change, perhaps v0.8.

**Comment by mfn** [comment]
Nevermind about 2) I mentioned. I don't have any references at hand; I mentioned this out of things I've experienced in the past with *lots of files* ( > 100.000). I know that FS limits are higher but performance degradation comes earlier. But maybe it's not true anymore. I know that Phorum employs this strategy which worked quite well for me: https://github.com/Phorum/Core/blob/master/include/api/cache/file.php .

It's a different issue any so sorry for mixing this in here. The 1) is real and you acknowledged to fix that, so great :-)

**Comment by mosbth** [comment]
So, there we go. The filename for the cached file, for remote files are, are now named using `md5()`. The original url is stored in the json-file.
Removed the use of filename extension.
