### ISSUE TITLE
Add support for redirections

### ISSUE THREAD

**Issue by mfn** [mosbth/cimage#87]
Sometimes images are further redirected but the current implementation doesn't take that into account.

https://github.com/mfn/cimage/commit/469c990674cb762605749763ad308da17b0d0515 could serve as an inspiration for an implementation.

**Comment by mosbth** [comment]
Yep, I'll check out your code and make up my own testcase for it.

**Comment by mosbth** [comment]
Thanks for this @mfn. I do appreciate it.
