### ISSUE TITLE
500 server error for png files

### ISSUE THREAD

**Issue by anil504** [mosbth/cimage#90]
Hi,

For the below type of png image we are getting 500 internal server error.
http://www.whatsonindia.com/WhatsOnTV/images/GenreImages/190x175/news.png

Can you please help me with this.

**Comment by mosbth** [comment]
Use development mode, or `webroot/imgd.php?src=news.png` to see a more verbose error message.

If that does not help, show how t reproduce the same error message (how are you using `img,php`?).

**Comment by anil504** [comment]
You can reproduced it by allowing remote files. Most of the png files and
other image files are working but some specific like the one I have posted
thorws 500 error and in debug mode gives error invalid file format

**Comment by anil504** [comment]
This is the exact error i am getting:

#	Time	Memory	Function	Location
1	0.0015	572352	{main}( )	..\img.php:0
2	0.0147	1368200	CImage->loadImageDetails( )	..\img.php:904
3	0.0148	1368280	getimagesize ( )	..\CImage.php:779
[img.php]
img.php: Uncaught exception:

The file doesn't seem to be a valid image.

#0 C:\wamp\www\crm\cimage\webroot\img.php(904): CImage->loadImageDetails()
#1 {main}

**Comment by mosbth** [comment]
The image link you provided actually does a redirect. The target link becomes:
http://images.whatsonindia.com/WhatsOnTV/images/GenreImages/190x175/news.png

The deal is to make `CHttpGet` support redirections.

This has been addressed in #87 and will be fixed there.

**Comment by mosbth** [comment]
So, its now fixed. 

If you still got issues, try adding the option `&no-cache` to force a reload and ignore the cached item.

Removing all files in `cache/remote` should also do the trick.
